spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: wb_239500
    # 可省略，SpringBoot自动推断
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/tools?serverTimezone=UTC

